services:
  - type: web
    name: apartment-ml-api
    env: python
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DATABASE
        value: test
      - key: MONGODB_COLLECTION
        value: properties
